name: Lint

on: [push, pull_request]

jobs:
  lintcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - uses: isort/isort-action@v1
      - name: Install poetry
        run: pip install poetry
      - name: Install mypy
        run: pip install mypy
      - name: Install requirements
        run: poetry install
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'lintcheck'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
